version: 2.1

orbs:
    clair-scanner: ovotech/clair-scanner@1.6.0

jobs:
    build:
        machine: true
        steps:
            - checkout

            - run:
                name: Build flask-docker-example image
                command: docker build -t flask-docker-example:latest .

    scan_images:
        executor: clair-scanner/default
        steps:
            - clair-scanner/scan:
                image: flask-docker-example:latest

workflows:
    version: 2
    build_and_scan:
        jobs:
            - build
            - scan_images
