
version: 2.1

orbs:
    clair-scanner: ovotech/clair-scanner@1.6.0

jobs:
    static-check:
        machine: true
        steps:
            - checkout

            - run:
                name: Dockerfile lint
                command: docker run --rm -i hadolint/hadolint < Dockerfile

    build:
        machine: true
        steps:
            - checkout

            - run:
                name: Build flask-docker-example image
                command: docker build -t jvrmaia/flask-docker-example:latest .

            - run:
                name: Build pylint image
                command: docker build -t pylint -f ./utils/pylint/Dockerfile ./utils/pylint/

            - run:
                name: pylint
                command: docker run --rm pylint /app

            - run:
                name: Login Docker Hub
                command: docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASS

            - run:
                name: Push image to Docker Hub
                command: docker push jvrmaia/flask-docker-example:latest

    scan_images:
        executor: clair-scanner/default
        steps:
            - clair-scanner/scan:
                image: jvrmaia/flask-docker-example:latest

workflows:
    version: 2
    build_and_scan:
        jobs:
            - static-check
            - build
            - scan_images
